### ISSUE TITLE
[Feat]: application properties 를 AWS secret manager 로 편리하게 관리하자. 

### ISSUE THREAD

**Issue by versatile0010** [Kusitms-NumberOne/Backend#17]
**Issue**
- 이슈 내용: 현재는 application.yml 등의 값의 변경이 생길 때 마다, 수동으로 전달해서 알려줘야하는 불편함이 존재한다. 보안적인 측면에서도 좋지 않다. AWS secret manager 로 application propreties 값을 관리하도록 한 다음, 로컬에서는 python script 를 실행해서 편리하게 (가장 최신의 properties 값을 ) 가져올 수 있도록 개선해보자.

**Branch Name**
- 생성 브랜치 이름 : `feat/get-secrets

**To-Do List**
- [ ] AWS secret manager 에 secret 값 등록
- [ ] get_secret.py 작성
- [ ] update_secret.py 작성
