### ISSUE TITLE
[Feat]: CI/CD 인프라를 구축한다.

### ISSUE THREAD

**Issue by versatile0010** [Kusitms-NumberOne/Backend#2]
**Issue**
- 이슈 내용: 인프라 구축

**Branch Name**
- 생성 브랜치 이름 : `feat/cicd`

**To-Do List**
- [x]  AWS setting I ( ec2, rds mysql, elastic IP, nginx )
- [x]  Project CI/CD setting ( git actions workflow, docker, docker compose)
- [x] Slack Alarm ( Every `build and deployment workflow` completes. ) 

![image](https://github.com/Kusitms-NumberOne/Backend/assets/96612168/ee7b7888-9753-457f-8ede-5958e37bf71f)
