### ISSUE TITLE
[Feat]: 인수 테스트 환경을 구축한다.

### ISSUE THREAD

**Issue by versatile0010** [Kusitms-NumberOne/Backend#28]
**Issue**
- 이슈 내용: API 품질 관리를 위해, 인수 테스트 환경을 구축한다.
- [인수 테스트란?](https://engineerinsight.tistory.com/98)

**Branch Name**
- 생성 브랜치 이름 : `feat/test`

**To-Do List**
- [x] 인수 테스트 환경 구축
- [x] Shelter api 에 대한 인수 테스트 코드 작성
- [ ] test/resources/application.yml 공유하기
