### ISSUE TITLE
[Feat]: 재난문자 api 개발

### ISSUE THREAD

**Issue by nohy6630** [Kusitms-NumberOne/Backend#43]
**Issue**
- 이슈 내용: 재난문자 api 개발

**Branch Name**
- 생성 브랜치 이름 : `feat/disaster_text`

**To-Do List**
- [x] 주기적 으로 실행되는 서비스로직을 만들어 주기적으로 재난문자 db에 데이터 갱신 
- [x] 위도, 경도를 기반으로 한 최근 재난문자 반환 api 구현
- [ ] db데이터를 이용하여 새로운 재난문자가 발생했을 경우 프론트에 데이터를 실시간으로 전송해야함. (sse vs web socket 어떤거 쓸지 의논 필요)

**Comment by versatile0010** [comment]
1. 주기적 으로 실행되는 서비스로직을 만들어 주기적으로 재난문자 db에 데이터 갱신 (서버 부하가 있다면 크롤링 로직은 다른 ec2로 빼야 할듯)
    - 이거 db 에 계속 쌓일텐데, 테이블 사이즈를 유지시키기 위해 주기적으로 다른 db 로 이관해주는 작업이 필요할 것 같아요.
    - 스프링 배치를 이용해서 구현하면 좋을 것 같아요

2. db데이터를 이용하여 새로운 재난문자가 발생했을 경우 프론트에 데이터를 실시간으로 전송해야함. (sse vs web socket 어떤거 쓸지 의논 필요)
    - 이 부분 어떻게 구현할 지, 논의하고 분담해서 진행해야 할 듯 합니다!
    - 아키텍쳐를 만들어놓고.. 작업해야 시간을 아낄 수 있을 듯 하네요
