### ISSUE TITLE
[Feat]: 후원 페이지 API

### ISSUE THREAD

**Issue by nohy6630** [Kusitms-NumberOne/Backend#51]
**Issue**
- 이슈 내용: 후원 페이지 API

**Branch Name**
- 생성 브랜치 이름 : `feat/sponsor`

**To-Do List**
- [x] 후원 데이터 구조 구축
- [x] 응원 데이터 구축 및 API 개발
- [x] 후원 페이지API 개발
