### ISSUE TITLE
[Feat]: 온보딩 API

### ISSUE THREAD

**Issue by nohy6630** [Kusitms-NumberOne/Backend#60]
**Issue**
- 이슈 내용: 온보딩 API

**Branch Name**
- 생성 브랜치 이름 : `feat/onboarding`

**To-Do List**
- [x] 닉네임 설정 api
- [x] 재난유형 설정 api
- [x] 지역 설정 api
- [x] (온보딩 관련은 아니지만) 회원가입시 소셜에서 사용자 이름 가져오기
