### ISSUE TITLE
[Feat]: 가족 API(알림 제외)

### ISSUE THREAD

**Issue by nohy6630** [Kusitms-NumberOne/Backend#63]
**Issue**
- 이슈 내용: 가족 API(알림 제외)

**Branch Name**
- 생성 브랜치 이름 : `feat/family`

**To-Do List**
- [ ] 가족 목록 조회 API
- [ ] 가족 추가 API
- [ ] 가족 삭제 API
- [ ] 가족 상태 갱신 API

**Comment by nohy6630** [comment]
아직 기획이 정해지지 않아서 일단 보류!
