### ISSUE TITLE
[Feat]: 실시간정보(GPS, 온오프라인) 관련 API

### ISSUE THREAD

**Issue by nohy6630** [Kusitms-NumberOne/Backend#70]
**Issue**
- 이슈 내용: 실시간정보(GPS, 온오프라인) 관련 API

**Branch Name**
- 생성 브랜치 이름 : `feat/realtime`

**To-Do List**
- [x] GPS 받아와서 해당 멤버의 갱신하는 데이터 api
- [x] 사용자 온오프상태 변동 api
- [x] 프론트에서 member id 저장을 위해 로그인시 멤버Id반환 하도록 api 수정
